version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: go-playground-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin